### ISSUE TITLE
[Bug] Submitit Local Launcher does not share jobs across GPUs

### ISSUE THREAD

**Issue by saydemr** [hydra-ecosystem/hydra#2757]
# 🐛 Bug
## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **
hydra/default.yaml
```
launcher:
  _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.LocalLauncher
  submitit_folder: ${hydra.sweep.dir}/.submitit/%j
  timeout_min: 60
  cpus_per_task: 1
  gpus_per_node: 4
  tasks_per_node: 1
  mem_gb: 8
  nodes: 1
  name: ${hydra.job.name}
```
config.yaml
```
defaults:
  - override hydra/launcher: submitit_local

hydra:
  job:
    n_trials: 50
    n_jobs: 4
```
Then run it with `python train.py -m`
** Stack trace/error message **
One GPU on the node gets all the jobs
![image](https://github.com/facebookresearch/hydra/assets/37012364/f91b02c5-9d8a-44b2-94af-94e1ce384c19)

## Expected Behavior
Each GPU on the node gets one job.

## System information
- **Hydra Version** :  1.3.2
- **Python version** :  3.8.15
- **Virtual environment type and version** : Miniconda 23.5.2
- **Operating system** : Ubuntu

## Additional context
- Env file, [environment.txt](https://github.com/facebookresearch/hydra/files/12727187/environment.txt) (yaml)
