### ISSUE TITLE
[Feature Request] Conditionally disable the creation of output folders via callback

### ISSUE THREAD

**Issue by HydrogenSulfate** [hydra-ecosystem/hydra#2846]
# 🚀 Feature Request

Add a python style configuration that prevents the creation of timestamped folder structures inside of outputs/ and multirun/ when executing a script decorated using @hydra.main().

## Motivation

**Is your feature request related to a problem? Please describe.**

I use hydra for ML jobs and it indeed convenient as folders are created with timestamp, but I guess an output directory is necessary when we are training/evaluating models but not model exporting/inference, because information printed during exporting and inference(such as a note for export success, path of product, inference progress) are much limited and only printing them to terminal is enough for most of users. So can we disable folder creation which is controlled by YAML.

for example, if we can control whether running directory is created by `mode`(when `mode` is "export" or "infer", running directory will not be created)?

``` yaml
hydra:
  run:
    # dynamic output directory according to running time and override name
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}/${hydra.job.override_dirname}
  job:
    name: ${mode} # name of logfile
    chdir: false # keep current working direcotry unchaned
  callbacks:
    init_callback:
      _target_: callbacks.InitCallback
  sweep:
    # output directory for multirun
    dir: ${hydra.run.dir}
    subdir: ./

# general settings
mode: train # running mode: train/eval/export/infer
```

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

## Additional context

Same feature request as #1937
