### ISSUE TITLE
[Help requested] Dynamic hydra launcher configuration

### ISSUE THREAD

**Issue by lwang2070** [hydra-ecosystem/hydra#2874]
Hello, thanks for your great work! It is incredibly helpful to use Hydra to configure experiments!

I am facing an issue, though, at the moment. I am using the Ray extension to launch my experiments, and trying to configure it such that different trials in the sweep request different resources, i.e.,

```
hydra:
  launcher:
    ray:
      remote:
        num_gpus: ${model.gpu_nums}
  sweeper:
    params:
      models: model_a, model_b
```
I tried various configurations but have not managed to make it work. I was wondering if this function is feasible with the current version.

Any help is appreciated! Thanks in advance!
