### ISSUE TITLE
[Feature Request] Allow partial instantiation with factories

### ISSUE THREAD

**Issue by hobbeshunter** [hydra-ecosystem/hydra#2981]
# 🚀 Feature Request

Add some way to not instantiate the whole config tree but stop when parameters are missing and create a factory (that needs to receive the missing parameters) instead.

## Motivation

I have a config tree with many target objects that I instantiate with hydra. However, sometimes it happens that a class has both: parameters that are config params and parameters that are just known at runtime. So it would be nice if hydra would detect when parameters are missing and return a factory instead.

## Pitch

I came up with a hacky solution that requires changes to omegaconf (see https://github.com/hobbeshunter/omegaconf/compare/master...hobbeshunter:omegaconf:non-strict-resolve) and hydra (see https://github.com/hobbeshunter/hydra/compare/main...hobbeshunter:hydra:instantiate-factory).

With a little helper class

```python
class Factory:

    def __init__(self, cfg: DictConfig):
        self._cfg = cfg
        self._cfg._set_flag(flags=["allow_objects", "struct", "readonly"],
                            values=[True, False, False])

    def __call__(self, _name_: str, **kwargs):
        cfg = OmegaConf.merge(self._cfg, kwargs)
        return instantiate(cfg.__getattr__(_name_), _convert_="object")
```

a config could look like:

```yaml
_target_: my_package.FactoryReceiver
  factory:
    _target_: hydra.utils.Factory
      _recursive_: false
      cfg:
        a: ???
        instance:
          _target_: my_package.BClass
            a: ${..a}
            b: 5
```

A `FactoryReceiver` could e.g. look like

```python
class FactoryReceiver:

    def __init__(self, factory: Factory):
        self._factory = factory

    def do_something(self):
        my_instance = self._factory(_name_="instance", a=7)
```

As can be seen above `FactoryReceiver` only has to know that it can instantiate an object named `instance` by providing an `a`. `Instance` can be arbitrarily complex.

IMHO that allows for nice parametrizable object composition.
